#!/bin/sh
#
# symlink this to additiona files as needed, matching scripts in

cat << EOF
********************************************************************
*                                                                  *
* This system is for the use of authorized users only.  Usage of   *
* this system may be monitored and recorded by system personnel.   *
*                                                                  *
********************************************************************

EOF

